### ISSUE TITLE
全部表示されるのがうざい

### ISSUE THREAD

**Issue by ghost** [aYosukeAkatsuka/acsmvc#1]
ランダムで一つだけ表示されるとかできませんか。

**Comment by aYosukeAkatsuka** [comment]
@aKosukeNagano 
コメントありがとうございます！
ランダムで一個だけ出力するオプション `-r` の実装を検討します。

**Comment by oHirokiKumamoto** [comment]
:+1:

**Comment by aYosukeAkatsuka** [comment]
@aKosukeNagano
@aHirokiKumamoto
`-r` オプションを実装しました。ランダムに一個だけ出力します。
お試しください！

**Comment by ghost** [comment]
:+1:
